spring:
  jpa:
    # prints delivered queries
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # runs data.sql after table creation
    defer-datasource-initialization: true